apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
spec:
  selector:
    matchLabels:
      app: python-app
  replicas: 1
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: python
        image: vilaspatel/pythonflask
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name:  python-app-service  
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: python-app   
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: python-app-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: python-app-service
          servicePort: 80
        path: /(.*)         