apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  nginx.conf: |
    server {
    listen       8090;
    server_name  localhost;
    access_log /dev/stdout;
    location / {
        root   /var/www;
        index  index.html index.htm;
    }
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
     }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: web-content-v1
data:
  index.html: |
    "Hello World v1"
---
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: web-content-v2
data:
  index.html: |
    "Hello World v2"
