name: Docker Image download

on: workflow_dispatch
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
jobs:

  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
   

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3    
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN1 }}
      - name: download ghcr image
        run: docker pull ghcr.io/vilaspatel/task:main
      - name: tag docker image 
        run: docker tag ghcr.io/vilaspatel/task:main ghcr.io/vilaspatel/task:v1.0.0
      - name: push docker image
        run: docker push ghcr.io/vilaspatel/task:v1.0.0
